from project.bakery import Bakery

bakery = Bakery('Random name')
print(bakery.add_food('Cake', 'Carrot Cake', 3.4))
print(bakery.add_food('Bread', 'Banana bread', 2.5))
print(bakery.add_food('Cake', 'Chocolate', 4.5))
print(bakery.add_table('OutsideTable', 55, 15))
print(bakery.reserve_table(10))
print(bakery.order_food(55, 'Carrot Cake', 'Banana bread', 'Chocolate', 'Rice pudding', 'pancakes'))
print(bakery.add_drink('Tea', 'Lemon tea', 20, "Lipton"))
print(bakery.add_drink('Water', 'Spring water', 30, "Devin"))
print(bakery.order_drink(55, 'Spring water', 'Lemon tea', 'Whiskey', 'vodka'))
print(bakery.add_table('OutsideTable', 56, 15))
print(bakery.add_table('InsideTable', 15, 10))
print(bakery.get_free_tables_info())