# Generated by Django 4.1.6 on 2023-02-13 20:03

import django.core.validators
from django.db import migrations, models
import expense_tracker.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            expense_tracker.core.validators.raise_if_not_letters,
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            expense_tracker.core.validators.raise_if_not_letters,
                        ],
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        default="/static/images/user.png",
                        null=True,
                        upload_to="profile_images/",
                        validators=[
                            expense_tracker.core.validators.validate_file_less_than_5MB
                        ],
                    ),
                ),
            ],
        ),
    ]
