# Generated by Django 4.1.6 on 2023-02-13 20:19

import django.core.validators
from django.db import migrations, models
import expense_tracker.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    expense_tracker.core.validators.raise_if_not_letters,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    expense_tracker.core.validators.raise_if_not_letters,
                ],
            ),
        ),
    ]
