# Generated by Django 4.1.6 on 2023-02-15 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_alter_userprofile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="budget",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
