# Generated by Django 4.1.5 on 2023-01-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0004_alter_photo_photo"),
        ("common", "0002_create_comment_and_like"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PhotoLikes",
            new_name="PhotoLike",
        ),
    ]
