# Generated by Django 4.1.5 on 2023-02-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_person_profile_image_alter_todo_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="persons"),
        ),
    ]
