# Generated by Django 4.1.5 on 2023-01-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="age",
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
    ]
