# Generated by Django 4.1.5 on 2023-01-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_employee_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.IntegerField(default=-1),
        ),
    ]
