# Generated by Django 4.1.5 on 2023-01-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="slug",
            field=models.SlugField(default="dep-1"),
            preserve_default=False,
        ),
    ]
