# Generated by Django 4.1.5 on 2023-01-16 14:12

from django.db import migrations, models
import models_demos.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_alter_department_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="start_date",
            field=models.DateField(
                validators=[models_demos.web.validators.validate_before_today]
            ),
        ),
    ]
