# Generated by Django 4.1.5 on 2023-01-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_employee_age_alter_employee_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
