# Generated by Django 4.1.5 on 2023-01-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_employee_works_full_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="level",
            field=models.CharField(
                choices=[("jr", "Junior"), ("reg", "Regular"), ("sr", "Senior")],
                default="Junior",
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="works_full_time",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
