# Generated by Django 4.1.5 on 2023-01-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_employee_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("code_name", models.CharField(max_length=10, unique=True)),
                ("deadline", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="projects",
            field=models.ManyToManyField(to="web.project"),
        ),
    ]
