# Generated by Django 4.1.5 on 2023-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_field_slug_for_existing_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
