# Generated by Django 4.1.7 on 2023-03-04 18:03

import car_collection.web.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SC", "Sports Car"),
                            ("PU", "Pickup"),
                            ("CO", "Crossover"),
                            ("MB", "Minibus"),
                            ("OTH", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            car_collection.web.validators.YearBetweenValidator(
                                1980, 2049
                            )
                        ]
                    ),
                ),
                ("image_url", models.URLField()),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "The username must be a minimum of 2 chars"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(18)]
                    ),
                ),
                ("password", models.CharField(max_length=30)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                ("profile_picture", models.URLField(blank=True)),
            ],
        ),
    ]
